#!/bin/bash

 grading(){
 grade=""
 remarks=""
 if [ $score -ge 80 ] && [ $score -le 100 ]
 then 
	grade="A"
	remarks="Excellent"
 elif [ $score -ge 75 ] && [ $score -le 79 ]
 then
	grade="A-"
	remarks="Excellent"
 elif [ $score -ge 70 ] && [ $score -le 74 ]
 then
	grade="B+"
	remarks="Good"
 elif [ $score -ge 65 ] && [ $score -le 69 ]
 then
	grade="B"
	remarks="Good" 
 elif [ $score -ge 60 ] && [ $score -le 64 ]
 then
	grade="B-"
	remarks="Pass" 
 elif [ $score -ge 55 ] && [ $score -le 59 ]
 then
	grade="C+"
	remarks="Pass"
 elif [ $score -ge 50 ] && [ $score -le 54 ]
 then
	grade="C"
	remarks="Pass"
 elif [ $score -ge 45 ] && [ $score -le 49 ]
 then
	grade="D"
	remarks="Failed" 
 elif [ $score -ge 40 ] && [ $score -le 44 ]
 then
	grade="E"
	remarks="Failed"
 elif [ $score -ge 0 ] && [ $score -le 39 ]
 then
	grade="F"
	remarks="Failed"
 elif [ $score -gt 100 ] || [ $score -lt 0 ]
 then
	echo "Invalid Marks Range!"
 fi
export grade
export remarks
}
